services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev --import-realm
    environment:
      JAVA_OPTS: "-XX:UseSVE=0"
    volumes:
      - ./tests/Fixtures/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - '8080:8080'
